In [8]:
import os
mingw_path = 'C:\\Program Files\\mingw-w64\\x86_64-5.3.0-posix-seh-rt_v4-rev0\\mingw64\\bin'
os.environ['PATH'] = mingw_path + ';' + os.environ['PATH']
%matplotlib inline
import pandas as pd
import numpy as np
from scipy import stats, integrate
import matplotlib.pyplot as plt
# import seaborn as sns
from numpy import sort
#import xgboost as xgb
from xgboost import XGBClassifier
from xgboost import XGBRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectFromModel
from sklearn.metrics import accuracy_score
from xgboost import plot_importance
from sklearn.decomposition import PCA
from sklearn.model_selection import GridSearchCV
import random
from sklearn import metrics, preprocessing
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score
from sklearn.cluster import KMeans

In [9]:
data_path = "F:\\Users\\ivann_000\\AnacondaProjects\\bk\\data"
X = pd.read_csv(data_path+"\\2017.csv", sep=',')
y = X['class'].values
X = X.drop(['class'], axis=1)

In [17]:
X_test = pd.read_csv(data_path+"\\2016_first_half.csv", sep=',')
y_test = X_test['class'].values
X_test = X_test.drop(['class'], axis=1)
model = XGBClassifier(seed=4242,
                      nthread=8,
                      colsample_bytree=1,
                      learning_rate=0.01,
                      max_depth=3,
                      n_estimators=50
                     )
model.fit(X, y)
pred = model.predict(X_test)
accuracy_score(pred, y_test)

0.50442477876106195

In [12]:
pred

array([0, 0, 2, 0, 0, 2, 0, 0, 0, 0], dtype=int64)

In [13]:
y_test

array([0, 0, 2, 0, 0, 2, 0, 0, 0, 1], dtype=int64)

In [16]:
X_test = pd.read_csv(data_path+"\\last_try.csv", sep=',')
X_test = X_test.fillna(0)
print(X_test)
# model = XGBRegressor(seed=4242,
#                       nthread=8,
#                       colsample_bytree=1,
#                       learning_rate=0.01,
#                       max_depth=3,
#                       n_estimators=50
#                      )
model = RandomForestRegressor()
model.fit(X, y)
pred = model.predict(X_test)
pred

     is_team_home_1  is_team_home_2  is_team_home_3  is_team_home_4  \
0 0               0               0               0               0   
  0               0               0               0               0   
  0               0               0               0               0   
  0               0               0               0               0   
  0               0               1               0               0   
  0               1               0               0               0   
  0               0               0               0               0   
  0               0               0               0               0   
1 0               0               0               0               0   
0 0               0               0               0               0   

     is_team_home_5  is_team_home_6  is_team_home_7  is_team_home_8  \
0 0               0               0               0               0   
  0               0               0               0               0   
  0  

array([ 1.6,  0.9,  0.6,  0.5,  0.3,  0.7,  0.9,  1. ,  0.8,  1.6])